// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvM3M7zUbQuLNVUaRhiKtKKw17Kk2ZNI',
    appId: '1:355680672439:web:0ac10a37cd334070864b32',
    messagingSenderId: '355680672439',
    projectId: 'testdatabase-b2a97',
    authDomain: 'testdatabase-b2a97.firebaseapp.com',
    storageBucket: 'testdatabase-b2a97.appspot.com',
    measurementId: 'G-P0L0R58VB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCod4Zk_GkEnuBc8_uEA8t5Rbxs4C_SLTc',
    appId: '1:355680672439:android:27ed4e6db1afa0dd864b32',
    messagingSenderId: '355680672439',
    projectId: 'testdatabase-b2a97',
    storageBucket: 'testdatabase-b2a97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC30ddp5l-3SBHD7yGFRmlN-sdC7qlsmdc',
    appId: '1:355680672439:ios:3e2ed820b2796353864b32',
    messagingSenderId: '355680672439',
    projectId: 'testdatabase-b2a97',
    storageBucket: 'testdatabase-b2a97.appspot.com',
    androidClientId: '355680672439-3e23milirg57tqbglbo5iiuj37sngn51.apps.googleusercontent.com',
    iosClientId: '355680672439-ign11eo4u21cf1c5nne4g9apdiet8818.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC30ddp5l-3SBHD7yGFRmlN-sdC7qlsmdc',
    appId: '1:355680672439:ios:3e2ed820b2796353864b32',
    messagingSenderId: '355680672439',
    projectId: 'testdatabase-b2a97',
    storageBucket: 'testdatabase-b2a97.appspot.com',
    androidClientId: '355680672439-3e23milirg57tqbglbo5iiuj37sngn51.apps.googleusercontent.com',
    iosClientId: '355680672439-ign11eo4u21cf1c5nne4g9apdiet8818.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
